### ISSUE TITLE
Display not found error.

### ISSUE THREAD

**Issue by doughnut9** [Wabri/polybar-minimal-nord-theme#1]
Hey, I'm kinda new to polybar so I couldn't fix this myself. Could you please tell me where I'm going wrong?

`error: Uncaught exception, shutting down: Monitor "HDMI-1" not found or disconnected`
`error: Uncaught exception, shutting down: Monitor "eDP-1-1" not found or disconnected`

**Comment by Wabri** [comment]
You need to change to your name monitor interface

**Comment by doughnut9** [comment]
Thank you very much!
